site_name: Surya Tesori & Accessori
site_url: https://alextesta00.github.io/PM-Surya/
site_author: Alex Testa

plugins:
  - search:
      lang: it

  - mermaid-to-svg:
      enabled_if_env: ENABLE_PDF_EXPORT
      image_id_enabled: true
      image_id_prefix: mermaid-diagram
      mermaid_config:
        htmlLabels: false
        flowchart:
          htmlLabels: false
        class:
          htmlLabels: false

  - to-pdf:
      cover: true
      cover_title: "Surya Tesori & Accessori"
      cover_subtitle: "Documentazione di Project Management"
      author: "Alex Testa"
      toc_title: "Indice"
      output_path: pdf/documentazione.pdf
      enabled_if_env: ENABLE_PDF_EXPORT

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.code.expand
    - content.code.focus
    - content.code.inherit
    - content.tabs.link
    - content.tabs.sticky
    - content.tooltips
    - content.toc.sticky
    - content.toc.follow
    - content.toc.highlight
    - content.toc.deep
    - content.toc.indent
    - content.toc.collapse
    - content.toc.expand
    - content.toc.sections
    - content.toc.smooth_scroll
    - content.toc.scrollspy
    - content.toc.scrollspy_offset

nav:
  - Introduzione:
    - Descrizione e Approccio: index.md
    - Contesto e Dominio: domain.md
  
  - Avvio e definizione del progetto:
    - Scoping & Meeting & Conditions Of Satisfaction: scoping_meeting_cos.md
    - Project Overview Statement: pos.md
    - Project Definition Statement: pds.md
  
  - Analisi e pianificazione:
    - Business Case & Analisi delle alternative: bc_and_aa.md
    - Requirements Breakdown Structure: rbs.md
    - Project Management Lifecycle: pmlc.md
    - Work Breakdown Structure: wbs.md
    - Stime, tempi, risorse e Costi: strc.md
    - GANTT & PERT & Project Network: gant_pert_pn.md
  
  - Governance e controllo:
    - Analisi dei rischi: risk.md
    - Matrice delle responsabilità RASCI: rasci.md
    - Piano di comunicazione & Scope change: scope_change.md
    - Monitoraggio e Controllo: monitoring.md
    - Issue Log: issue.md
  
  - Esecuzione e chiusura:
    - Launching and Execution: le.md
    - Closing: closing.md
    - Report Finale: final_report.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format