site_name: Surya Tesori & Accessori
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.code.expand
    - content.code.focus
    - content.code.inherit
    - content.tabs.link
    - content.tabs.sticky
    - content.tooltips
    - content.toc.sticky
    - content.toc.follow
    - content.toc.highlight
    - content.toc.deep
    - content.toc.indent
    - content.toc.collapse
    - content.toc.expand
    - content.toc.sections
    - content.toc.smooth_scroll
    - content.toc.scrollspy
    - content.toc.scrollspy_offset

nav:
  - Introduzione:
    - Contesto e Dominio: domain.md
  
  - Avvio e definizione del progetto:
    - Scoping & Meeting & Conditions Of Satisfaction: scoping_meeting_cos.md
    - Project Overview Statement: pos.md
    - Project Definition Statement: pds.md
  
  - Analisi e pianificazione:
    - Business Case & Analisi delle alternative: bc_and_aa.md
    - Requirements Breakdown Structure: rbs.md
    - Project Management Lifecycle: pmlc.md
    - Work Breakdown Structure: wbs.md
    - Stime, tempi, risorse e Costi: strc.md
    - Gant & Project Network: gant_pn.md
  
  - Governance e controllo:
    - Analisi dei rischi: risk.md
    - Matrice delle responsabilità RASCI: rasci.md
    - Piano di comunicazione & Scope change: scope_change.md
  
  - Esecuzione e chiusura:
    - Launching and Execution: le.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format